meta:
  title: What's for dinner API
  description: Keeping track of your ingredients on hand to make easier dinner preparation decisions.
  siteUrl: https://docs.whatsfordinner.dev
  keywords: api reference docs
logo: ./images/logo.png
enableToc: true
oasDefinitions:
  dinner: https://api.redoc.ly/registry/testing_acme/whatsfordinner/1.0.0/bundle/main/openapi.yaml
  # add links to definitions in our API registry by using a fully qualified URL.
stylesheets:
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap
  - https://fonts.googleapis.com/css?family=Source+Code+Pro:400,600,700&display=swap
nav:

  - label: Quickstart
    page: docs/quickstart.md

  - label: About this site
    icon: ./images/redocly-icon-white.png
    page: made-in-austin.md

  - search: true

footer:
  copyrightText: Copyright © Redocly 2019-2021. All right reserved.
  columns:
    - group: Legal
      items:
        - label: Terms of Use
          href: 'https://redoc.ly/subscription-agreement/'
        - label: Privacy Notice
          href: 'https://redoc.ly/privacy-policy/'
        - label: Cookie Notice
          href: 'https://redoc.ly/privacy-policy/'
    - group: Support
      items:
        - label: FAQ
          page: faq.md
        - label: Contact us
          page: contact.mdx
